### ISSUE TITLE
Incorrect line(s) for fire damage and crash when exiting the game

### ISSUE THREAD

**Issue by ghost** [HugoZink/PD2_VocalHeisters#1]
First issue:
I'm uncertain if this is an actual "issue," but whenever the player gets fire damage*, it will trigger the tear gas line, which is rather erroneous and/or inaccurate. I presume there's no actual line(s) from getting fire damage, so maybe it would be _better_ to remove it instead?

*Every fire damage, including Thermite and the burning money on Firestarter Day 3. Molotov does not trigger the line, however.
Example:
https://youtu.be/RKa-MkHMkcY

Second issue:
Application has crashed: C++ exception
mods/VocalHeisters/vocalheisterscore.lua:49: attempt to index a nil value

SCRIPT STACK

SayOnce() @mods/VocalHeisters/vocalheisterscore.lua:56
functionCall() @mods/VocalHeisters/lua/groupaistatebase.lua:10
Update() @mods/base/req/core/DelayedCalls.lua:24
func() @mods/base/req/core/DelayedCalls.lua:10
Call() @mods/base/req/core/Hooks.lua:109
update() @mods/base/lua/GameSetup.lua:6
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

The game crashed after I exited from an online heist. I'm not sure why, but this occurred after I installed the "Narrator Anticipation Restoration" mod.

**Comment by morerokk** [comment]
Fire triggering the teargas lines is a known issue that I'm currently working on. The reason it happens is because the game calls the same code for teargas and fire. I'm testing a possible fix right now. Thanks for your report!

There are sadly no voice lines for being burned by fire, so for now this won't trigger *any* voice lines at all anymore.

The other crash you mentioned is rather odd, this must be some super-specific condition that happens if you quit during an assault anticipation. I blame BLT for not writing their "Is Ingame" functions correctly. I'll add more nil checks so it shouldn't crash anymore.

Thanks for your detailed reports!

**Comment by morerokk** [comment]
Fixed.
